### PR TITLE
fix(omg-cli): [regression] omg subscribe

### LINKED ISSUE #244: [regression] omg subscribe
See:
- https://github.com/microservices/python-events/pull/1
- https://github.com/microservices/node-events/pull/1

It boils down to:

```
INFO:werkzeug:172.17.0.1 - - [19/Jul/2019 15:30:24] "GET /health HTTP/1.1" 200 -
INFO:__main__:[subscribe] id: "205215a8-8594-4904-85d3-5355dfd82249", endpoint:"http://172.17.0.2:4042", name: "heartbeat", data: {}
INFO:werkzeug:172.17.0.1 - - [19/Jul/2019 15:30:24] "POST /events HTTP/1.1" 200 -
INFO:__main__:[publish] name: "heartbeat", data: {'user': 'max', 'time': '2019-07-19 15:30:27.770808'}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

### PR DESCRIPTION
**Pull request by Arinono**
Fixes #244

### CODE REVIEW

File: tests/regression/bin/omg/omg [hunk 1]
```diff
@@ -0,0 +1,3 @@
+#!/usr/bin/env node
+
+require('../../../../packages/omg/dist/cli/program').parse(process.argv)
```
Comment (wilzbach) [inline tests/regression/bin/omg/omg]: Why double nested?

File: tests/regression/test.sh [hunk 2]
```diff
@@ -14,18 +20,24 @@ mkdir repos
 cd repos
 for repo in clojure d go node java python php ruby rust scala ; do
     echo "===== Testing $repo ====="
-    git clone -q --depth 1 "https://github.com/microservices/${d}.git"
+    git clone -q "https://github.com/microservices/${repo}.git"
```
Comment (wilzbach) [inline tests/regression/test.sh]: You want to use --depth 1 for faster clones and less bandwidth abuse.

File: tests/regression/bin/omg/omg (hunk 1 above)
Comment (Arinono) [reply tests/regression/bin/omg/omg]: Because on OSX, I cannot execute `jq` (since it's a linux binary). This way I can add the condition to use the provided jq binary or the one I have locally

File: tests/regression/test.sh (hunk 2 above)
Comment (Arinono) [reply tests/regression/test.sh]: Ok. And why there was a ${d}, because it was empty on my side ?

File: tests/regression/bin/omg/omg (hunk 1 above)
Comment (Arinono) [reply tests/regression/bin/omg/omg]: Removed the double nesting for omg, it was not necessary.
